"""Support round-trip flights

Revision ID: 45c8406c675a
Revises: 6af4b678b935
Create Date: 2025-08-03 07:21:49.607276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45c8406c675a'
down_revision = '6af4b678b935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_seats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'flights', ['flight_id'], ['flight_id'])

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_type', sa.Enum('One_way', 'Round_trip', name='triptype'), nullable=False))
        batch_op.drop_constraint(batch_op.f('reservations_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('flight_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('reservations_ibfk_1'), 'flights', ['flight_id'], ['flight_id'])
        batch_op.drop_column('trip_type')

    with op.batch_alter_table('reservation_seats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flight_id')

    # ### end Alembic commands ###
