"""Initial migration

Revision ID: 609a04b51484
Revises: 
Create Date: 2025-08-03 01:25:19.035135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609a04b51484'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('IATA_code', sa.String(length=10), nullable=False),
    sa.Column('ICAO_code', sa.String(length=10), nullable=False),
    sa.Column('support_email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('airline_id')
    )
    op.create_table('airports',
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('IATA_code', sa.String(length=10), nullable=False),
    sa.Column('ICAO_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('airport_id')
    )
    op.create_table('passengers',
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('passport_no', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('passenger_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aircrafts',
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.airline_id'], ),
    sa.PrimaryKeyConstraint('aircraft_id')
    )
    op.create_table('flight_template',
    sa.Column('flight_template_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('departure_airport_id', sa.Integer(), nullable=False),
    sa.Column('arrival_airport_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.aircraft_id'], ),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.airline_id'], ),
    sa.ForeignKeyConstraint(['arrival_airport_id'], ['airports.airport_id'], ),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['airports.airport_id'], ),
    sa.PrimaryKeyConstraint('flight_template_id')
    )
    op.create_table('seats',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('class_', sa.Enum('Economy', 'Business', 'First', name='seatclass'), nullable=False),
    sa.Column('position', sa.Enum('Window', 'Aisle', 'Middle', name='seatposition'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.aircraft_id'], ),
    sa.PrimaryKeyConstraint('seat_id')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_template_id', sa.Integer(), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=False),
    sa.Column('timezone_diff', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['flight_template_id'], ['flight_template.flight_template_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('prices',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('flight_template_id', sa.Integer(), nullable=False),
    sa.Column('economy_price', sa.Float(), nullable=False),
    sa.Column('business_price', sa.Float(), nullable=False),
    sa.Column('first_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['flight_template_id'], ['flight_template.flight_template_id'], ),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('flight_template_id')
    )
    op.create_table('discounts',
    sa.Column('discount_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.PrimaryKeyConstraint('discount_id')
    )
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.DateTime(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('Confirmed', 'Cancelled', 'Refunded', name='reservationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_table('reservation_seats',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.passenger_id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.reservation_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.seat_id'], ),
    sa.PrimaryKeyConstraint('reservation_id', 'passenger_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_seats')
    op.drop_table('invoices')
    op.drop_table('reservations')
    op.drop_table('discounts')
    op.drop_table('prices')
    op.drop_table('flights')
    op.drop_table('seats')
    op.drop_table('flight_template')
    op.drop_table('aircrafts')
    op.drop_table('users')
    op.drop_table('passengers')
    op.drop_table('airports')
    op.drop_table('airlines')
    # ### end Alembic commands ###
