"""Add name field to User

Revision ID: 6af4b678b935
Revises: 609a04b51484
Create Date: 2025-08-03 04:38:53.601539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6af4b678b935'
down_revision = '609a04b51484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'passenger'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'passenger'"))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
