"""added flighttype column to flight_template

Revision ID: 7caf93ff8664
Revises: 45c8406c675a
Create Date: 2025-08-03 07:26:24.375406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caf93ff8664'
down_revision = '45c8406c675a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_type', sa.Enum('Domestic', 'International', name='flighttype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_template', schema=None) as batch_op:
        batch_op.drop_column('flight_type')

    # ### end Alembic commands ###
